#marketing jdbc≈‰÷√
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myredis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: HD6Mz0mR9SY2m7z/pOsJfGIz0BxyQHWgIMnFqlhDIfRTKtb0wfLxs1ian0Y0fO2EU6AFp6KxkuraMKaiM0/qKQ==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ6wO1skpAb+5FmWffmODK0if1zxDONkezmNlbzOg8xXY8PwHUjK3uk3cZqSOofF6XQwBQ3arxwv2OnfsVCPqEUCAwEAAQ==
    driverClassName: com.mysql.jdbc.Driver
    filters: config
    maxActive: 450
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 120000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT * FROM baseconfig where id = 'imgfilerelativepath';
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 100
    removeAbandoned: true
    removeAbandonedTimeout: 300
    logAbandoned: true
  redis:
    redis:
      database: 3
      host: 127.0.0.1
      port: 6379
      password: 123456
    timeout: 30000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 300
        min-idle: 0
server:
  port: 8083
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml